projects:
  default:
    schema:
      - http://localhost:4000/graphql:
          headers:
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUwMDMyMTQ3LCJleHAiOjE3NTA2MzY5NDd9.wTpcP_NL65YBWvRePOKjgNfYEkKDt7Gx0q2NdXWsBRk
    extensions:
      endpoints:
        default:
          url: http://localhost:4000/graphql
