version: "3.9"

services:
  ats-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ats-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
