import { Job } from './columns';

export const jobData: Job[] = [
    {
        id: 'job-2',
        title: 'Mobile Developer',
        description: 'Figma & Prototyping Expert',
        status: 'DRAFT',
        type: 'Contract',
        applicants: 21,
        createdAt: '2024-12-26T09:58:26',
    },
    {
        id: 'job-3',
        title: 'Data Scientist',
        description: 'Automation & Manual Testing',
        status: 'OPEN',
        type: 'Part-time',
        applicants: 17,
        createdAt: '2025-01-16T15:18:00',
    },
    {
        id: 'job-4',
        title: 'QA Engineer',
        description: 'Node.js + GraphQL + Prisma',
        status: 'CLOSED',
        type: 'Full-time',
        applicants: 19,
        createdAt: '2025-06-12T18:35:19',
    },
    {
        id: 'job-5',
        title: 'Product Manager',
        description: 'React + Django Stack',
        status: 'DRAFT',
        type: 'Part-time',
        applicants: 33,
        createdAt: '2025-06-16T10:56:31',
    },
    {
        id: 'job-6',
        title: 'Product Manager',
        description: 'Automation & Manual Testing',
        status: 'DRAFT',
        type: 'Contract',
        applicants: 39,
        createdAt: '2025-03-15T05:51:14',
    },
    {
        id: 'job-7',
        title: 'QA Engineer',
        description: 'Node.js + GraphQL + Prisma',
        status: 'DRAFT',
        type: 'Full-time',
        applicants: 35,
        createdAt: '2025-03-09T23:05:28',
    },
    {
        id: 'job-8',
        title: 'Product Manager',
        description: 'AWS + Docker + CI/CD',
        status: 'CLOSED',
        type: 'Part-time',
        applicants: 23,
        createdAt: '2025-01-07T12:06:58',
    },
    {
        id: 'job-9',
        title: 'Data Scientist',
        description: 'Node.js + GraphQL + Prisma',
        status: 'CLOSED',
        type: 'Full-time',
        applicants: 28,
        createdAt: '2025-05-05T20:23:44',
    },
    {
        id: 'job-10',
        title: 'ML Engineer',
        description: 'Python + TensorFlow',
        status: 'CLOSED',
        type: 'Contract',
        applicants: 33,
        createdAt: '2025-06-17T05:44:18',
    },
    {
        id: 'job-11',
        title: 'QA Engineer',
        description: 'React + Tailwind Developer',
        status: 'OPEN',
        type: 'Full-time',
        applicants: 48,
        createdAt: '2025-06-01T10:45:30',
    },
    {
        id: 'job-12',
        title: 'UI/UX Designer',
        description: 'Deep Learning + PyTorch',
        status: 'DRAFT',
        type: 'Part-time',
        applicants: 24,
        createdAt: '2025-05-26T17:52:26',
    },
    {
        id: 'job-13',
        title: 'UI/UX Designer',
        description: 'Python + TensorFlow',
        status: 'CLOSED',
        type: 'Part-time',
        applicants: 3,
        createdAt: '2025-06-01T19:36:11',
    },
    {
        id: 'job-14',
        title: 'ML Engineer',
        description: 'React + Tailwind Developer',
        status: 'DRAFT',
        type: 'Contract',
        applicants: 32,
        createdAt: '2025-03-12T08:09:48',
    },
    {
        id: 'job-15',
        title: 'Backend Engineer',
        description: 'Agile PM with JIRA',
        status: 'CLOSED',
        type: 'Part-time',
        applicants: 14,
        createdAt: '2025-04-26T19:56:34',
    },
    {
        id: 'job-16',
        title: 'Full Stack Developer',
        description: 'Agile PM with JIRA',
        status: 'OPEN',
        type: 'Contract',
        applicants: 30,
        createdAt: '2025-02-02T00:10:55',
    },
    {
        id: 'job-17',
        title: 'QA Engineer',
        description: 'React + Tailwind Developer',
        status: 'OPEN',
        type: 'Contract',
        applicants: 48,
        createdAt: '2025-05-27T08:14:26',
    },
    {
        id: 'job-18',
        title: 'Product Manager',
        description: 'React + Django Stack',
        status: 'DRAFT',
        type: 'Part-time',
        applicants: 7,
        createdAt: '2025-03-12T22:28:54',
    },
    {
        id: 'job-19',
        title: 'Full Stack Developer',
        description: 'Figma & Prototyping Expert',
        status: 'CLOSED',
        type: 'Full-time',
        applicants: 50,
        createdAt: '2025-05-27T08:42:53',
    },
    {
        id: 'job-20',
        title: 'UI/UX Designer',
        description: 'AWS + Docker + CI/CD',
        status: 'OPEN',
        type: 'Contract',
        applicants: 11,
        createdAt: '2025-03-21T09:35:01',
    },
    {
        id: 'job-21',
        title: 'Frontend Developer',
        description: 'Deep Learning + PyTorch',
        status: 'OPEN',
        type: 'Full-time',
        applicants: 47,
        createdAt: '2025-04-08T15:19:36',
    },
    {
        id: 'job-22',
        title: 'DevOps Engineer',
        description: 'Figma & Prototyping Expert',
        status: 'CLOSED',
        type: 'Full-time',
        applicants: 35,
        createdAt: '2024-12-31T02:27:54',
    },
    {
        id: 'job-23',
        title: 'Mobile Developer',
        description: 'Figma & Prototyping Expert',
        status: 'CLOSED',
        type: 'Contract',
        applicants: 1,
        createdAt: '2025-05-21T01:13:15',
    },
    {
        id: 'job-24',
        title: 'UI/UX Designer',
        description: 'Agile PM with JIRA',
        status: 'OPEN',
        type: 'Contract',
        applicants: 13,
        createdAt: '2025-03-16T10:08:05',
    },
    {
        id: 'job-25',
        title: 'Mobile Developer',
        description: 'AWS + Docker + CI/CD',
        status: 'OPEN',
        type: 'Contract',
        applicants: 47,
        createdAt: '2025-06-07T02:59:13',
    }
]

