import { Applicant } from './columns';

export const applicantData: Applicant[] = [
    {
        id: 'app-2',
        name: 'Lindsay Marshall',
        email: 'zhood@yahoo.com',
        stage: 'SHORTLISTED',
        position: 'Data Scientist',
        appliedAt: '2025-01-11T05:10:29',
    },
    {
        id: 'app-3',
        name: 'Emily Diaz',
        email: 'lisa80@yahoo.com',
        stage: 'INTERVIEWED',
        position: 'Data Scientist',
        appliedAt: '2025-05-16T19:46:16',
    },
    {
        id: 'app-4',
        name: 'Sarah Cruz',
        email: 'jesse75@dalton.com',
        stage: 'REJECTED',
        position: 'Data Scientist',
        appliedAt: '2025-02-18T09:32:00',
    },
    {
        id: 'app-5',
        name: 'Nicole Lewis',
        email: 'keith60@hotmail.com',
        stage: 'APPLIED',
        position: 'Backend Engineer',
        appliedAt: '2025-01-27T19:21:01',
    },
    {
        id: 'app-6',
        name: 'Andre Leach',
        email: 'jason23@hotmail.com',
        stage: 'HIRED',
        position: 'Data Scientist',
        appliedAt: '2025-01-13T18:56:29',
    },
    {
        id: 'app-7',
        name: 'Donna Johnson',
        email: 'patriciapotter@yahoo.com',
        stage: 'INTERVIEWED',
        position: 'UI/UX Designer',
        appliedAt: '2025-04-16T16:03:18',
    },
    {
        id: 'app-8',
        name: 'Catherine Young',
        email: 'sharpallen@weiss.com',
        stage: 'HIRED',
        position: 'Data Scientist',
        appliedAt: '2025-02-19T09:06:39',
    },
    {
        id: 'app-9',
        name: 'Michelle Craig',
        email: 'ncharles@martinez.com',
        stage: 'REJECTED',
        position: 'Frontend Developer',
        appliedAt: '2025-04-14T05:32:40',
    },
    {
        id: 'app-10',
        name: 'Ashlee Randolph',
        email: 'skinnerdonna@anderson.com',
        stage: 'HIRED',
        position: 'DevOps Engineer',
        appliedAt: '2024-12-30T09:20:03',
    },
    {
        id: 'app-11',
        name: 'Jonathan Bowers',
        email: 'hwolf@hotmail.com',
        stage: 'INTERVIEWED',
        position: 'Frontend Developer',
        appliedAt: '2025-03-25T06:37:35',
    },
    {
        id: 'app-12',
        name: 'Megan Rogers',
        email: 'cmcdaniel@yahoo.com',
        stage: 'HIRED',
        position: 'DevOps Engineer',
        appliedAt: '2025-02-13T03:38:49',
    },
    {
        id: 'app-13',
        name: 'George Lopez',
        email: 'chenrichard@miller.com',
        stage: 'SHORTLISTED',
        position: 'Backend Engineer',
        appliedAt: '2025-06-06T08:12:02',
    },
    {
        id: 'app-14',
        name: 'Lori Thompson',
        email: 'xfrazier@diaz.org',
        stage: 'APPLIED',
        position: 'Frontend Developer',
        appliedAt: '2024-12-17T11:06:01',
    },
    {
        id: 'app-15',
        name: 'Mr. Ryan Flowers',
        email: 'reginagonzales@gmail.com',
        stage: 'HIRED',
        position: 'Data Scientist',
        appliedAt: '2025-05-07T04:33:18',
    },
    {
        id: 'app-16',
        name: 'Kelsey Lynn',
        email: 'irussell@gmail.com',
        stage: 'INTERVIEWED',
        position: 'Backend Engineer',
        appliedAt: '2025-02-03T04:01:06',
    },
    {
        id: 'app-17',
        name: 'Adam Berger',
        email: 'george91@hotmail.com',
        stage: 'HIRED',
        position: 'Frontend Developer',
        appliedAt: '2025-03-17T15:11:52',
    },
    {
        id: 'app-18',
        name: 'Jason Hamilton',
        email: 'joanacosta@villa.com',
        stage: 'INTERVIEWED',
        position: 'Data Scientist',
        appliedAt: '2025-04-08T00:30:35',
    },
    {
        id: 'app-19',
        name: 'Matthew Foster',
        email: 'lrobinson@nguyen.net',
        stage: 'APPLIED',
        position: 'UI/UX Designer',
        appliedAt: '2025-04-06T19:39:43',
    },
    {
        id: 'app-20',
        name: 'Dr. Mallory Baxter',
        email: 'melissahudson@hotmail.com',
        stage: 'INTERVIEWED',
        position: 'Backend Engineer',
        appliedAt: '2025-05-08T03:02:02',
    },
    {
        id: 'app-21',
        name: 'Joel Schneider',
        email: 'crystal75@george.com',
        stage: 'REJECTED',
        position: 'DevOps Engineer',
        appliedAt: '2025-02-04T05:54:16',
    },
    {
        id: 'app-22',
        name: 'Daniel Gonzalez',
        email: 'stephanieatkins@brown.com',
        stage: 'INTERVIEWED',
        position: 'Backend Engineer',
        appliedAt: '2025-06-07T23:26:18',
    },
    {
        id: 'app-23',
        name: 'Crystal Webster',
        email: 'lucasbrian@walker.com',
        stage: 'SHORTLISTED',
        position: 'Data Scientist',
        appliedAt: '2025-05-25T22:12:48',
    },
    {
        id: 'app-24',
        name: 'Jennifer Vasquez',
        email: 'donaldacevedo@hotmail.com',
        stage: 'SHORTLISTED',
        position: 'Backend Engineer',
        appliedAt: '2025-04-25T10:31:22',
    },
    {
        id: 'app-25',
        name: 'Martha Lewis',
        email: 'andrea11@yahoo.com',
        stage: 'SHORTLISTED',
        position: 'UI/UX Designer',
        appliedAt: '2025-06-03T05:16:20',
    }
]
  